version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: datagen_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/app
    networks:
      - app-network
    volumes:
      - ./:/var/www/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
 

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: datagen_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: datagen_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: datagen
      MYSQL_ROOT_PASSWORD: sifre123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  dbdata:
    driver: local